### ISSUE TITLE
Cache is not updated when running on local node

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-ts#205] opened 2022-02-18 09:09 UTC
**Describe the bug**
Market orders do not update the cached OB when running a local node

**To Reproduce**
1. fork mumbai
2. start a repl session with Mangrove.js
3. buy something on a non empty market
4. consoleAsks() shows offers that have been consumed already

**Expected behavior**
Using the API on a local node should behave as using the API on a distant node

**Additional context**
API behaves as expected when running directly against mumbai

**Comment by jkrivine** [comment] 2022-03-10 10:55
```javascript
const env = require("dotenv").config();
const { Mangrove } = require("@mangrovedao/mangrove.js");
const ethers = require("ethers");
let provider = new ethers.providers.WebSocketProvider(
  env.parsed.MUMBAI_NODE_URL
);
```

**Comment by espendk** [comment] 2022-05-23 13:39
I think this is related to #164: Sometimes ethers.js or hardhat fails to provide the right logs for the last block.

**Comment by espendk** [comment] 2022-05-23 14:59
Pretty sure this is caused by the `WebSocketProvider` issue described in #197 and reported to ethers.js here: https://github.com/ethers-io/ethers.js/issues/3012

**Comment by espendk** [comment] 2023-01-26 20:02
Closing this as a duplicate of #197

**Closed by espendk** 2023-01-26 20:02 UTC
Labels: bug
